version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: st124784-ml-assignmnet2
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]